language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '13'
  - '12'
  - '10'
branches:
  only:
    - master
    - /^greenkeeper.*$/
script:
  - yarn verify
  - ./scripts/run-on-node-version.sh 13 "npm install -g codacy-coverage && cat ./coverage/lcov.info | codacy-coverage"
  - ./scripts/run-on-node-version.sh 13 "npm install -g coveralls && cat ./coverage/lcov.info | coveralls"
